version: '3.9'

services:
  postgres:
    image: postgres:14.2
    container_name: ship-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pwd
    networks:
      - ship
    ports:
      - "5433:5432"
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    container_name: ship-api
    build:
      context: .
      dockerfile: app/Api.Sql/Dockerfile
    networks:
      - ship
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:3001
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
    command: ["dotnet", "ef", "database update"]
networks:
  ship:
    name: ship
