version: '3.8'

services:
  mongo:
    image: mongo:4.2
    container_name: ship-mongo
    command: --replSet ship-rs --bind_ip_all
    networks:
      - ship
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  replicator:
    container_name: ship-replicator
    build: ./replicator
    depends_on:
      - mongo
    links:
      - "mongo"
    networks:
      - ship
  api:
    container_name: ship-api
    build:
      context: .
      dockerfile: app/Api.NoSql/Dockerfile
    networks:
     - ship
    depends_on:
      - "replicator"
    links:
      - "mongo"
  signal-r:
    container_name: ship-signal-r
    build:
      context: .
      dockerfile: app/SignalR/Dockerfile
    networks:
     - ship
    volumes:
      - "./src:/app/src"
    depends_on:
      - "api"
    links:
      - "api"
networks:
  ship:
    name: ship_network