version: '3.6'

services:
  mongo:
    image: mongo:4.2
    container_name: ship-mongo
    command: --replSet ship-rs --bind_ip_all
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootPassword
    networks:
      - ship
    ports:
      - "27017:27017"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  api:
    container_name: ship-api
    build:
      context: .
      dockerfile: app/Api/Dockerfile
    networks:
     - ship
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:3001
    volumes:
      - "./src:/app/src"
    ports:
      - "3001:3001"
    depends_on:
      - "mongo"
    links:
      - "mongo"
  signal-r:
    container_name: ship-signal-r
    build:
      context: .
      dockerfile: app/SignalR/Dockerfile
    networks:
     - ship
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8082
    volumes:
      - "./src:/app/src"
    ports:
      - "8082:8082"
    depends_on:
      - "api"
    links:
      - "api"
networks:
  ship:
    name: ship_network