version: '3.6'

services:
  mongo:
    image: mongo:4.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootPassword
    networks:
      - ship
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
networks:
  ship:
    name: ship_network
volumes:
  mongodata: