version: '3.8'

services:
  postgres:
    image: postgres:14.2
    container_name: ship-postgres
    networks:
      - ship
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    container_name: ship-api
    build:
      context: .
      dockerfile: app/Api.Sql/Dockerfile
    networks:
      - ship
    depends_on:
      postgres:
        condition: service_healthy
    command: ["dotnet", "ef", "database update"]
networks:
  ship:
    name: ship